### ISSUE TITLE
Add include_fields option

### ISSUE THREAD

**Issue by masalmon** [ropenscilabs/ropenaq#22]

**Comment by masalmon** [comment]
Now I can have sourceName or attribution or averagingPeriod but when I set all three arguments to TRUE, I don't get any of these pieces of information. I create a string, i.e. I use "sourceName" or "attribution&sourceName". I have also tried "attribution%2CaveragingPeriod". With "sourceName" I get source name information in the output, but with "attribution%2CaveragingPeriod" I don't get anything.

@jflasher is there anything I should know about passing the value of "include_fields"? I see it's an array but I'm stuck.

**Comment by jflasher** [comment]
Format should be `https://api.openaq.org/v1/measurements?include_fields=sourceType,averagingPeriod`

**Comment by masalmon** [comment]
Oh a "," ok, many thanks @jflasher ! 😀
