### ISSUE TITLE
Make it easier to get a lot of data

### ISSUE THREAD

**Issue by masalmon** [ropenscilabs/ropenaq#6]
For now the functions are only wrapper to API queries and I cannot output more than 1000 lines. Maybe I should modify my functions so that no matter how big the table it can be delivered by my function, by making several queries: e.g. if the user wants all measurements in a given city in one year I could make one query for each day and then bind the results for the user.

@jflasher, will there always be the 1000 limit? I guess it's for avoiding too many big queries that could slow everything down?

**Comment by masalmon** [comment]
This would also mean making it possible to get results for several cities at the same time...As suggested here. https://github.com/ropensci/onboarding/issues/24#issuecomment-176629959

**Comment by jflasher** [comment]
Addressed this a bit in https://github.com/openaq/openaq-api/issues/169#issuecomment-177303507 but I think you'd probably want to handle paging of results and making more than one query to get the data.

**Comment by masalmon** [comment]
So if I put say limit=1000 and page=2 I can get 2000 lines? Sorry for asking such an easy question. :-)

**Comment by jflasher** [comment]
You'll still only ever get at most `limit` results, so in this case, you'd get results 1001 to 2000.

**Comment by masalmon** [comment]
Oooh this is what I hadn't understood. This is really, really cool: I can then loop over the different pages and get everything if needed. Thank you (for your answer and your patience), I had really missed the point here!

**Comment by jflasher** [comment]
Yep exactly! :)

**Comment by masalmon** [comment]
Now there is a page argument in `aq_measurements` and a warning if found>limit.

**Comment by masalmon** [comment]
I have updated the documentation and I think that's the best solution for helping people to get a lot of data. I don't want to implement this automatically.

I should just add the link to the csv dump files now.

**Comment by jflasher** [comment]
CSV dumps should be close, just need to get around to looking into https://github.com/openaq/openaq-api/pull/197

**Comment by masalmon** [comment]
Cool! Currently I have written "If you really need a lot of data, you might consider downloading the csv files that contain all measurements per location from [this link](https://openaq.org/#/sources)."

**Comment by jflasher** [comment]
👍 Just a heads up that doesn't give you 'all' measurements, just the last 65,000 or so, which for some places is all, but for others is not.

**Comment by masalmon** [comment]
Oh so for now I'll erase the link and add one again when the csv thing you mentioned is ready. Thanks a lot!
